[package]
name = "req"
version = "0.1.0"
authors = ["axylos <robertdraketalley@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"reqwest" = "0.9.19"
"serde_json" = "1.0"
"serde" = "1.0.60"
